<a href="https://colab.research.google.com/github/Abhishek-world/Pytorch-and-Tensorflow-with-Google-Colab/blob/master/Pytorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import matplotlib.pyplot as plt

**Initiliasing Tensors**

In [ ]:
x=torch.ones(3,2)
print(x)
y=torch.zeros(3,2)
print(y)
z=torch.rand(3,2)
print(z)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0.4560, 0.3182],
        [0.8949, 0.3061],
        [0.3366, 0.1756]])


In [ ]:
x=torch.empty(3,2)
print(x)
y=torch.zeros_like(x)
print(y)

tensor([[4.9004e-37, 0.0000e+00],
        [4.4842e-44, 0.0000e+00],
        [       nan, 6.4460e-44]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [ ]:
x=torch.ones(3,2)
y=torch.ones(3,2)
z=x+y
print(z)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


In [ ]:
p=x.add(y)

In [ ]:
print(p)
print(x)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [ ]:
q=x.add_(y)
print(q)
print(x)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


**Numpy<>Pytorch**

In [ ]:
x_np=x.numpy()
print(type(x_np))

<class 'numpy.ndarray'>


In [ ]:
a_pt=torch.from_numpy(x_np)
print(type(a_pt))

<class 'torch.Tensor'>


Now if You will change on a_pt it will also make change in x_np

In [ ]:
%%time
for i in range(100):
  x=np.random.randn(100,100)
  y=np.random.randn(100,100)
  c=x+y

CPU times: user 93.2 ms, sys: 0 ns, total: 93.2 ms
Wall time: 97 ms


In [ ]:
%%time
for i in range(100):
  a=torch.randn(100,100)
  b=torch.randn(100,100)
  d=a+b

CPU times: user 18.4 ms, sys: 0 ns, total: 18.4 ms
Wall time: 19.1 ms


**cuda support**

In [ ]:
print(torch.cuda.device_count())

1


In [ ]:
print(torch.cuda.device(0))
print(torch.cuda.get_device_name(0))

Tesla P100-PCIE-16GB


In [ ]:
cuda0=torch.device('cuda:0')

In [ ]:
a=torch.ones(3,2,device=cuda0)
b=torch.ones(3,2,device=cuda0)
c=a+b
print(c)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]], device='cuda:0')


In [ ]:
x=torch.ones([3,2],requires_grad=True)

In [ ]:
y=x+5
print(y)

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)


In [ ]:
z=y*y+1
print(z)

tensor([[37., 37.],
        [37., 37.],
        [37., 37.]], grad_fn=<AddBackward0>)


In [ ]:
t=torch.sum(z)
print(t)

tensor(222., grad_fn=<SumBackward0>)


In [ ]:
t.backward()

In [ ]:
print(x.grad)

tensor([[12., 12.],
        [12., 12.],
        [12., 12.]])


In [ ]:
x=torch.ones([3,2],requires_grad=True)
y=x+5
r=1/(1+torch.exp(-y))
print(r)
t=torch.sum(r)
t.backward()
print(x.grad)

tensor([[0.9975, 0.9975],
        [0.9975, 0.9975],
        [0.9975, 0.9975]], grad_fn=<MulBackward0>)
tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])
